### ISSUE TITLE
Bug: 'npm run build:d' occur error in 'npm run relay -- --watch'

### ISSUE THREAD

**Issue by gee05053** [lablup/backend.ai-webui-ossca-2023#1]
### What Operating System(s) are you seeing this problem on?

Linux (x86-64)

### Backend.AI version

23.09.0-alpha1

### Describe the bug

1. watchman not installed
when I ran `npm run build:d`, I got error like below image
![watchman설치안했을 때](https://github.com/lablup/backend.ai-webui-ossca-2023/assets/28584221/af327275-6bf2-497f-a9ad-628b9848ed76)

2. watchman installed
  when I ran `npm run build:d` I got error message like below images
![watchman 설치했을 때1](https://github.com/lablup/backend.ai-webui-ossca-2023/assets/28584221/11d121dc-f769-44a2-88a0-bf0406dc0add)
![watchman 설치했을 때2](https://github.com/lablup/backend.ai-webui-ossca-2023/assets/28584221/b9ec5f34-1394-48b1-96ca-a4bcbc2c777c)
![스크린샷 2023-07-10 22-09-53](https://github.com/lablup/backend.ai-webui-ossca-2023/assets/28584221/cec9db6a-76f5-41ee-a3c0-8c5efbb332bf)

### To Reproduce

1-1. npm i
1-2. npm run build:d

2-1. sudo apt-get install watchman
2-2. npm i
2-3. npm run build:d

### Expected Behavior

`npm run build:d` will run well without error like below image
![스크린샷 2023-07-10 22-19-52](https://github.com/lablup/backend.ai-webui-ossca-2023/assets/28584221/0d3535e0-cfd0-4ce5-9492-f787410c3c95)

### Anything else?

I tried I didn't install watchman and I modified package.json
from
`"scripts": {
       ...
       ...
       "build:d": "npm run patchLib && npx concurrently -c \"auto\" --names \"webcomponent,react-relay,react\" \"./node_modules/typescript/bin/tsc --watch\" \**"cd react && npm run relay -- --watch\"** \"cd react && npm start\"",
       ...}`
to
`"scripts": {
       ...
       ...
       "build:d": "npm run patchLib && npx concurrently -c \"auto\" --names \"webcomponent,react-relay,react\" \"./node_modules/typescript/bin/tsc --watch\" \**"cd react && npm run relay --watch\"** \"cd react && npm start\"",
       ...}`
`npm run build:d` ran well without error like below image
![스크린샷 2023-07-10 22-19-52](https://github.com/lablup/backend.ai-webui-ossca-2023/assets/28584221/44648ced-84b6-461d-89ca-2062b0257642)

**Comment by yomybaby** [comment]
Did you install Watchman using `apt`?  If so, it might be an old version.
```
Warning: Do not install the Ubuntu-supplied Watchman package. It is old and missing security, bug, and performance fixes.
```

On [documentation](https://facebook.github.io/watchman/docs/install#homebrew), 
```
If you use Homebrew on Linux, it's a great way to get a recent Watchman build.
```

I suggest you install Watchman again using Homebrew and try again. I installed Watchman using Homebrew on Linux today, and it worked properly.

**Comment by gee05053** [comment]
I solved this issue, when I tried to install watchman by following the [document](https://facebook.github.io/watchman/docs/install#homebrew)!!
Thank you so much.

**Comment by gee05053** [comment]
I reopen this Issue because Many people have same problem
I will modify README.md

**Comment by gee05053** [comment]
Sorry... I noticed watchman installation guide already wrote.
Close the Issue again..
