### ISSUE TITLE
Tab Menus disappear from session page when size is reduced

### ISSUE THREAD

**Issue by gee05053** [lablup/backend.ai-webui-ossca-2023#2]
### What Operating System(s) are you seeing this problem on?

Linux (x86-64)

### Backend.AI version

23.09.0-alpha2

### Describe the bug

when page size is reduced, Tab Menus disappear from session page and can't click menus

![스크린샷 2023-07-25 00-28-09](https://github.com/lablup/backend.ai-webui-ossca-2023/assets/28584221/66a24b52-115e-4bff-8bc8-00cac79a12e4)
Full size

![스크린샷 2023-07-25 00-30-27](https://github.com/lablup/backend.ai-webui-ossca-2023/assets/28584221/fc57a887-8463-46f8-9a27-0a8556dac2e7)
Reduced size

### To Reproduce

1. Login page and click "session" menu on the side
2. Try resized web page size
3. You can see you can't click disappeared tab menus

### Expected Behavior

Even if session page size is reduced, you can click tab menus

**Comment by yomybaby** [comment]
Thank you for issuing. 
After scrolling horizontally through the tabs, you can see the other tabs. 😉
